/*!
 * p-insel – Language Switcher
 * DE / EN  |  localStorage key: pi-lang
 */
(function () {
  'use strict';

  const LANG_KEY = 'pi-lang';

  /* ──────────────────────────────────────────
     TRANSLATIONS
     Add new keys to both 'de' and 'en' blocks.
     HTML is allowed in values.
  ────────────────────────────────────────── */
  const T = {
    de: {
      /* Nav & drawer */
      'nav.home':        'Home',
      'nav.portfolio':   'Portfolio',
      'nav.about':       'Über mich',
      'nav.faq':         'FAQ',
      'nav.contact':     'Kontakt',
      'nav.cta':         'Termin anfragen',
      'drawer.cta':      'Termin anfragen',

      /* Hero */
      'hero.line1':      'DEIN',
      'hero.line2':      'TATTOO.',
      'hero.line3':      'FÜR IMMER.',
      'hero.sub':        'Surrealismus / Cover Up / Black &amp; Grey',
      'hero.location':   'Tattoo Atelier · Bad Lippspringe',
      'hero.cta1':       'Termin anfragen',
      'hero.cta2':       'Portfolio ansehen',
      'hero.quote':      'EIN TATTOO IST <span style="color:var(--accent);">DAS EINZIGE</span> WAS DU<br>DIR <span style="color:var(--accent);">IN DEINEM LEBEN</span> GÖNNST OHNE ES<br>JE WIEDER ZU VERLIEREN…',

      /* Stats bar (hero meta strip) */
      'stats.experience': 'Erfahrung',
      'stats.tv':          'Im Fernsehen',
      'stats.unique':      'Unikate',
      'stats.since':       'Selbstständig',
      'stats.events':      'Events',
      'stats.rating':      'Bewertung',

      /* About section (index) */
      'about.eyebrow':  'Die Künstlerin',
      'about.h2':       'Pia Insel –<br><span>Tätowiererin</span><br>&amp; Malerin',
      'about.quote':    '„Pia Insel ist eine außergewöhnlich talentierte Tätowiererin (…), die für ihre Fähigkeiten in den Stilen Aquarell, Illustration und Realismus bekannt ist. Ihre Arbeit ist ein Beweis für ihre Hingabe und Fähigkeit, die Vision jedes Kunden auf seiner Haut zum Leben zu erwecken."',
      'about.cite':     '— Tattoo Wizard',
      'about.cta':      'Mehr über Pia',
      'tag.realismus':  'Realismus',
      'tag.tierportraits': 'Tierportraits',
      'tag.surrealismus': 'Surrealismus',
      'tag.dino':       'Dinosaurier',
      'tag.farbsw':     'Farbe &amp; SW',

      /* Stats section (index) */
      'stats.label1':   'Jahre Erfahrung',
      'stats.label2':   'Unikate',
      'stats.label3':   'Messen &amp; Events',
      'stats.label4':   'Google Bewertung',

      /* Portfolio teaser (index) */
      'portfolio.eyebrow': 'Portfolio',
      'portfolio.title':   'Ausgewählte <span>Arbeiten</span>',
      'portfolio.all':     'Alle Arbeiten',
      'tag.bunt':    'Bunt',
      'tag.sw':      'Schwarz-Weiß',
      'tag.coverup': 'Cover-Up',
      'tag.malerei': 'Malerei',

      /* SWR section */
      'swr.eyebrow':    'Bekannt aus dem TV',
      'swr.title':      'Pia Insel im <span>Fernsehen</span>',
      'swr.desc':       'Pia Insel gleich zwei mal zu Gast beim SWR – Bei „Kaffee oder Tee" sprach sie über das Thema Organspende und bei Pierre M. Krause sorgte sie für „gute Unterhaltung".',
      'swr.card1.title':'Pia Insel beim SWR',
      'swr.card1.desc': 'Der SWR stellt gern Persönlichkeiten vor die besonderes machen. Was Tattoos mit Organspende zu tun haben.',
      'swr.card2.title':'Pia Insel beim SWR',
      'swr.card2.desc': 'Für gute Unterhaltung sorgte Pia als Überraschungsgast zum Thema Freundschaft.',
      'swr.yt.label':   'Auf YouTube ansehen',

      /* Testimonials */
      'reviews.eyebrow': 'Kundenstimmen',
      'reviews.title':   'Was Kunden <span>sagen</span>',
      'review1.text':  'Pia ist eine absolut tolle Künstlerin. Mega sympathisch, ich hatte sofort vollstes Vertrauen zu ihr. Das Atelier ist klein und fein, sauber und gemütlich. Und ihre Arbeit ist mega schön geworden.',
      'review1.name':  'Claudia S.',
      'review1.meta':  'Google Bewertung · ★★★★★',
      'review2.text':  'Tattoostudio mit einzigartiger, zauberhafter Atmosphäre. Pia ist super nett, herzlich, offen und unterhaltsam, ihre Insel ist ein warmer Wohlfühlort. Ich freue mich schon auf das nächste Mal!',
      'review2.name':  'Katrin Tonollo',
      'review2.meta':  'Google Bewertung · ★★★★★',
      'review3.text':  'Pia hat sich da nicht einfach nur ein Studio, sondern einen Wohlfühl-Ort aufgebaut. Super schönes Ding. Pia wie immer sehr sympathisch und gut gelaunt!',
      'review3.name':  'Jacqueline Bischel',
      'review3.meta':  'Google Bewertung · ★★★★★',

      /* Maps */
      'maps.eyebrow':    'Anfahrt',
      'maps.title':      'FINDE DAS TATTOO ATELIER <span>FÜR DEINE AUSZEIT</span>',
      'maps.desc':       'Das Atelier liegt mitten in Bad Lippspringe – direkt an der Detmolder Straße, gut erreichbar mit Auto und Bus.',
      'maps.address':    'Adresse',
      'maps.hours':      'Öffnungszeiten',
      'maps.hours.val':  'Nach Vereinbarung',
      'maps.gmaps':      'In Google Maps öffnen',

      /* Process */
      'process.eyebrow':  'So funktioniert\'s',
      'process.title':    'Dein Weg zum <span>Tattoo</span>',
      'process.s1.title': 'Termin-Release abwarten',
      'process.s1.desc':  'Ich vergebe Termine nur einmal pro Quartal – Da ich alles alleine organisiere bitte ich herzlich um deine Geduld. Es wird sich lohnen.',
      'process.s2.title': 'Inspiration sammeln',
      'process.s2.desc':  'Such dir vorab Referenzbilder raus, die deinen Wunschstil zeigen. Zum Beispiel Fotos vom Haustier, Blumen oder Actionfigur.',
      'process.s3.title': 'Anfrage schicken',
      'process.s3.desc':  'Sobald die Termine online gehen, schickst du mir deine Anfrage über das <a href="kontakt.html" style="color:var(--accent);text-decoration:none;">Kontaktformular</a>.',
      'process.s4.title': 'Termin sichern',
      'process.s4.desc':  'Wenn alles passt, bekommst du deinen Termin bestätigt. Dann heißt es nur noch: Vorfreude genießen und den Countdown starten.',

      /* Footer */
      'footer.about':        'Tattoo Studio in Bad Lippspringe – Wo Kunst entsteht und Momente für die Ewigkeit festgehalten werden. Pia Insel, Tätowiererin &amp; Malerin.',
      'footer.nav.title':    'Navigation',
      'footer.styles.title': 'Stile',
      'footer.contact.title':'Kontakt',
      'footer.nav.home':     'Startseite',
      'footer.nav.portfolio':'Portfolio',
      'footer.nav.about':    'Über mich',
      'footer.nav.styles':   'Stile &amp; Techniken',
      'footer.nav.contact':  'Kontakt',
      'footer.s.colorful':   'Bunt',
      'footer.s.bw':         'Schwarz-Weiß',
      'footer.s.surreal':    'Surrealismus &amp; Farbe',
      'footer.s.coverup':    'Cover-Ups',
      'footer.hours.label':  'Termine',
      'footer.hours.val':    'Nach Vereinbarung',

      /* Cookie */
      'cookie.text':    'Diese Website verwendet keine Tracking-Cookies. Nur technisch notwendige Daten werden verarbeitet.',
      'cookie.accept':  'Verstanden',
      'cookie.decline': 'Schließen',

      /* ── KUENSTLERIN PAGE ── */
      'k.hero.eyebrow':  'Die Künstlerin',
      'k.hero.h1':       'Wer ist <span>Pia Insel?</span>',
      'k.about.eyebrow': 'Über mich',
      'k.about.h2':      'PIA <span>INSEL</span>',
      'k.about.sub':     'Tätowiererin · Bühnenmalerin · Träumerin mit Nadel.',
      'k.about.p1':      'Ich mag <strong style="color:var(--text);">echte Menschen</strong>, gute Gespräche und <strong style="color:var(--text);">ehrliche Energie</strong>. Privat reise ich gern und verschieden, denn ich mag alle Jahreszeiten und nahezu jede Landschaft. Ich verbringe meine Freizeit genauso gern auf Konzerten wie zuhause mit Katastrophendokus oder komplett unnötigem aber spannenden Erdkundewissen.',
      'k.about.p2':      'Durch meine Arbeit durfte ich bereits die Crew von Künstlern wie <strong style="color:var(--text);">Rammstein, Peter Maffay oder Jan Delay</strong> tätowieren — und genau diese Mischung aus Kreativität, Menschen und besonderer Atmosphäre erfüllt mich. Privat und Arbeit verbunden... Selbst- und ständig. So heißt es doch!',
      'k.about.p3':      'Mein Kater <strong style="color:var(--text);">Balu</strong> lebt in der festen Überzeugung, ein Hund zu sein, was mich im Alltag regelmäßig an die frische Luft zwingt. Er ist <strong style="color:var(--text);">mein Star</strong> und ich bin unendlich dankbar für ihn!',
      'k.about.p4':      'Ich falle weniger durch Zurückhaltung auf, verteile <strong style="color:var(--text);">gute Laune</strong> und habe eine ausgeprägte Schwäche für <strong style="color:var(--text);">Dinosaurier</strong>.<br>Zwischen Lachen und Deep Talk bewege ich mich dabei erstaunlich mühelos.',
      'k.about.cta':     'Jetzt Termin anfragen',
      'k.tag.realismus':    'Realismus',
      'k.tag.tierportraits':'Tierportraits',
      'k.tag.surrealismus': 'Surrealismus',
      'k.tag.dino':         'Dinosaurier',
      'k.tag.farbsw':       'Farbe &amp; SW',
      'k.tag.catmom':       'Cat Mom',
      'k.tag.ontour':       'On Tour',
      'k.tag.pinsel':       'Pinsel',

      /* Milestones */
      'k.milestones.eyebrow': 'Werdegang',
      'k.milestones.title':   'Meilensteine',
      'k.m1.year':  '2015',
      'k.m1.title': 'Selbstständigkeit',
      'k.m1.desc':  '2015 wagte ich den Schritt in die Selbstständigkeit als Tätowiererin. Nach 12 Jahren Bühnenmalerei begann ein neues Kapitel.',
      'k.m2.year':  '2016 – heute',
      'k.m2.title': 'Tattoo-Messen europaweit',
      'k.m2.desc':  'Ich plane regelmäßige Teilnahme an internationalen Tattoo-Conventions und Messen quer durch Europa.',
      'k.m3.year':  '2021',
      'k.m3.title': 'Eigenes Atelier',
      'k.m3.desc':  'Nach einigen Jahren im Austausch mit Kollegen in verschiedenen Tattoostudios eröffnete ich 2021 mein eigenes kleines Privat-Atelier — wegen dem Wortspiel liebevoll die Insel genannt.',
      'k.m4.year':  'Heute',
      'k.m4.title': 'Zurück in der Heimat',
      'k.m4.desc':  'Glücklich wieder in der alten Heimat angekommen zu sein und gespannt auf die tollen Projekte, die auf mich warten.',

      /* USP cards */
      'k.usp.eyebrow':  'Warum p-insel',
      'k.usp.title':    'Was mich <span>auszeichnet</span>',
      'k.usp1.title':   'Künstlerischer Hintergrund',
      'k.usp1.desc':    '12 Jahre Bühnenmalerei prägen jedes meiner Tattoos. Komposition, Tiefe und Perspektive sind mein Fundament.',
      'k.usp2.title':   'Beratung mit Empathie',
      'k.usp2.desc':    'Auch wenn wir uns erst an deinem großen Tag treffen, heißt das nicht, dass du vorab nur eine Nummer bist. Genau das macht deinen Termin und dein Tattoo am Ende so besonders.',
      'k.usp3.title':   'Hygiene &amp; Sicherheit',
      'k.usp3.desc':    'Sterile Einwegmaterialien, zertifizierte Farben und ein sauberes Studio. Deine Gesundheit hat höchste Priorität.',
      'k.usp4.title':   'Messen &amp; Wettbewerbe',
      'k.usp4.desc':    'Regelmäßig auf internationalen Tattoo-Conventions. Dort wo die besten Artists der Szene zusammenkommen.',

      /* Motto / quote */
      'k.motto':      '„Heute ist Dein Tag. Mach mal Urlaub!<br>Dein Souvenir wirst du ewig tragen."',
      'k.motto.attr': '— Pia Insel',

      /* CTA band */
      'k.cta.eyebrow':   'BEREIT FÜR DEIN TATTOO?',
      'k.cta.title':     '',
      'k.cta.btn':       'TERMIN ANFRAGEN',

      /* ── FAQ PAGE ── */
      'faq.hero.eyebrow': 'Häufige Fragen',
      'faq.hero.h1':      'Alles was du<br><em>wissen musst</em>',
      'faq.hero.sub':     'Fragen zur Vorbereitung und dem Ablauf? Hier findest du Antworten.',

      /* FAQ questions */
      'faq.q1': 'Was kostet ein Tattoo von Pia Insel?',
      'faq.q2': 'Lehnst du auch etwas ab?',
      'faq.q3': 'Wie finde ich heraus, ob du meinen Cover-up Wunsch erfüllst?',
      'faq.q4': 'Wie lange dauert ein Tattoo-Termin?',
      'faq.q5': 'Wie zahle ich?',
      'faq.q6': 'Wie bereite ich mich auf den Termin vor?',
      'faq.q7': 'Wie pflege ich mein neues Tattoo?',

      /* FAQ answers */
      'faq.a1.p1': '<span style="color:#ffffff;font-weight:700;">Jedes Tattoo ist unterschiedlich</span> und hängt von einigen Faktoren ab: welche Körperstelle tätowiert wird, wie groß es ist und ob es mehr oder weniger bunt werden soll. Hier sind ein paar Bildbeispiele. Kleinere Motivanfragen werden selbstverständlich preislich angepasst.',
      'faq.a1.p2': 'Vor allem der Unterschied zwischen einem neuen Tattoowunsch und einem Cover-up (ein altes Tattoo überstechen) ist nicht zu unterschätzen. Ein Cover-up bedeutet Mehraufwand.',
      'faq.price.bunt':   'Bunte Tattoos &amp; Surrealismus',
      'faq.price.coverup':'Cover-up Arbeiten',
      'faq.price.sw':     'Schwarzweiß­arbeiten',
      'faq.a2.p1': 'Ich nehme nur Projekte an, die meinem Stil entsprechen. Also kommst du mit einer Pinterest-Vorlage und sagst: „ich will genau das" — wird das nicht passieren. <strong>Inspiration dürfen wir uns holen, aber wir betreiben keinen Kunstraub!</strong>',
      'faq.a2.p2': 'Ich behalte mir vor, einzelne Schriften, Symbole und alle Motive, die mir keinen <span style="color:#ffffff;font-weight:700;">kreativen Freiraum</span> geben, abzulehnen. Auch Stellen wie Finger, hinter dem Ohr oder alles unterhalb des Fußknöchels tätowiere ich nicht.',
      'faq.a3.p1': 'Für solche besonderen Fälle biete ich außerhalb der Terminvergabe <strong>Online-Beratungen</strong> an. Nur die Beratung — der Termin folgt erst zur Quartalsvergabe.',
      'faq.a3.p2': 'Schreib mir dazu bitte eine E-Mail mit:',
      'faq.a3.li1': 'einem Foto deines vorhandenen Tattoos',
      'faq.a3.li2': 'Bilder deiner Idee',
      'faq.a3.li3': 'einer kurzen Info, wie du es dir vorstellst',
      'faq.a3.mail': 'Mail: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'faq.a4.p1': 'Für eine Tagessitzung planst du einen Aufenthalt von ca. <strong>6 Stunden</strong> — stressfreie Me-Time, ohne Unterbrechungen, damit ich mich voll und ganz auf deinen Tattootraum konzentrieren kann.',
      'faq.a4.p2': 'Ein Beispiel: Für einen kompletten Arm (Sleeve) brauche ich ca. <strong>4–6 Termine</strong>. Pro Tagestermin schaffe ich ca. eine <strong>DIN-A4-große Fläche</strong> als Orientierung.',
      'faq.a5.p1': 'Es kann <strong>bar</strong> oder per <strong>Sofortüberweisung (Online-Banking)</strong> gezahlt werden. Ratenzahlung wird nicht akzeptiert.',
      'faq.a5.p2': 'Bezahlt wird am Ende des Termines. Brichst du deine Sitzung ungeplant ab, hast du keinen Anspruch auf einen reduzierten Preis.',
      'faq.a6.li1':  '<span style="color:#ffffff;font-weight:700;">Freu dich drauf!</span>',
      'faq.a6.li2':  'Komme ausgeruht und stressfrei zu deinem Termin',
      'faq.a6.li3':  'Gönn dir vorher etwas Leckeres und Gesundes — nichts Schweres',
      'faq.a6.li4':  'Bring bei längeren Sitzungen gerne einen Snack mit',
      'faq.a6.li5':  'Trage dunkle, bequeme Kleidung — z.B. einen Hoody, den man von vorne anziehen kann, bei rückenfreien Motiven',
      'faq.a6.li6':  '<strong>Das Atelier ist eine schuhfreie Zone</strong> — dicke Socken oder Puschen mitbringen',
      'faq.a6.li7':  'Bring ein Handtuch mit',
      'faq.a6.li8':  'Bei Nervosität: Kopfhörer und Lieblingsmusik einpacken',
      'faq.a6.li9':  'Vertraue auf deine Künstlerin',
      'faq.a6.li10': '<strong>Quality-time-Modus an!</strong>',
      'faq.a7.p1': 'Hast du endlich dein lang ersehntes Tattoo, erkläre ich dir alles Wichtige zur Wundversorgung. Ab diesem Moment bist du alleine für die Versorgung und Abheilung verantwortlich.',
      'faq.a7.p2': 'Die vollständige Pflegeanleitung kannst du hier als PDF herunterladen:',
      'faq.q8': 'Welche Grundvoraussetzungen gibt es für einen Termin?',
      'faq.a8.p1': 'Damit dein Termin auf der Insel reibungslos läuft, gibt es ein paar Grundvoraussetzungen:',
      'faq.a8.li1': 'Tätowiert wird erst <strong>ab dem 18. Lebensjahr</strong>',
      'faq.a8.li2': 'Du solltest dich <strong>gesundheitlich in einem guten Zustand</strong> befinden',
      'faq.a8.li3': 'Tattoos in der <strong>Schwangerschaft und Stillzeit</strong> sind tabu',
      'faq.a8.li4': '<strong style="color:var(--text);">Verzichte</strong> vor deinem Termin auf <strong>blutverdünnende und immunschwächende Medikamente oder Lebensmittel</strong> (z.B. Aspirin / Alkohol), <strong>Betäubungsalben</strong> und <strong>Sonnenbaden</strong>',
      'faq.q9':      'Bekomme ich vorher mein Motiv geschickt?',
      'faq.a9.p1':   'Den endgültigen Entwurf zeige ich an dem Tag, an dem es auch gestochen wird. Es ist immer <strong>genügend Zeit</strong> eingeplant, um Änderungswünsche vorzunehmen! Niemand setzt dich unter Druck – und bitte scheu dich nicht, etwas anzusprechen.',
      'faq.a9.p2':   'Dieses Vorgehen hat sich in mehr als 12 Jahren sehr bewährt. Deine genaue Beschreibung und mein künstlerisches Sehen sind das <strong>beste Zusammenspiel</strong>.',
      'faq.pdf.title': 'Pflegeanleitung herunterladen',
      'faq.pdf.sub':   'PDF · Tattoo Nachsorge von Pia Insel',

      /* FAQ CTA */
      'faq.cta.eyebrow': 'Bereit?',
      'faq.cta.title':   'Dein nächstes Tattoo<br><span>wartet auf dich</span>',
      'faq.cta.desc':    'Schick mir deine Idee – und wir erschaffen gemeinsam etwas,<br>das du ein Leben lang tragen wirst.',
      'faq.cta.btn':     'Terminanfrage senden',

      /* ── KONTAKT PAGE ── */
      'kon.hero.eyebrow': 'Termin anfragen',
      'kon.hero.h1':      'Lass uns <span>loslegen</span>',
      'kon.hero.sub':     'Beschreib mir deine Idee – ich melde mich so schnell wie möglich zurück. Kostenlose Erstberatung inklusive.',
      'kon.info.eyebrow': 'So erreichst du mich',
      'kon.info.h2':      'Kontakt &amp;<br><span>Infos</span>',
      'kon.label.address':'Adresse',
      'kon.label.hours':  'Öffnungszeiten',
      'kon.hours.val':    'Nach Vereinbarung',
      'kon.pdf.title':    'Pflegeanleitung herunterladen',
      'kon.pdf.sub':      'PDF · Tattoo Nachsorge von Pia Insel',
      'kon.form.booking': 'Buchungsfenster',
      'kon.form.name':    'Name *',
      'kon.ph.name':      'Dein Name',
      'kon.form.email':   'E-Mail *',
      'kon.ph.email':     'deine@email.de',
      'kon.form.stil':    'Tattoo-Stil',
      'kon.form.groesse': 'Ungefähre Größe',
      'kon.form.koerper': 'Körperstelle',
      'kon.ph.koerper':   'z.B. Rücken, Schulter, Wade, Unterarm …',
      'kon.form.idee':    'Deine Idee *',
      'kon.form.idee.ph': '• Hauptmotiv\n• Wichtige Details oder Elemente\n• Gewünschte Stimmung/Wirkung\n• Was unbedingt enthalten sein soll\n• Was du nicht im Motiv haben möchtest\n• Wunschterminzeitraum',
      'kon.form.refs':    'Referenzbilder (optional)',
      'kon.opt.please':   '– Bitte wählen –',
      'kon.stil.bunt':    'Bunt / Farbig',
      'kon.stil.sw':      'Schwarz-Weiß',
      'kon.stil.coverup': 'Cover-Up',
      'kon.size.a5':      'DIN A5 (ca. Handfläche)',
      'kon.size.a4':      'DIN A4 (ca. Oberarm)',
      'kon.size.arm':     'Ganzer Arm / Sleeve',
      'kon.size.bein':    'Ganzes Bein',
      'kon.size.ruecken': 'Ganzer Rücken',
      'kon.body.unterarm':'Unterarm',
      'kon.body.ruecken': 'Rücken',
      'kon.body.schulter':'Schulter',
      'kon.body.wade':    'Wade',
      'kon.upload.text':  'Bilder hier ablegen oder <span style="color:var(--accent)">klicken</span>',
      'kon.upload.hint':  'JPG, PNG, HEIC — max. 5 MB pro Datei',
      'kon.form.returning': 'Warst du schon mal bei mir?',
      'kon.opt.yes':       'Ja',
      'kon.opt.no':        'Nein',
      'kon.form.hint':    '<strong style="color:var(--text);">Kurzer Hinweis vor dem Absenden:</strong><br>Viele Fragen rund um Preise, Stile, Cover-Ups und Termine werden im <a href="faq.html" style="color:var(--accent);">FAQ</a> beantwortet. Schau dort gerne noch einmal rein – vielleicht ist deine Frage schon dabei!',
      'kon.dsgvo':        'Ich habe die <a href="datenschutz.html" style="color:var(--accent);">Datenschutzerklärung</a> gelesen und bin mit der Verarbeitung meiner Daten einverstanden. *',
      'kon.submit':       'Anfrage absenden',
      'kon.mandatory':    '* Pflichtfelder · Keine Weitergabe deiner Daten an Dritte',
      'kon.success.h3':   'Anfrage eingegangen!',
      'kon.success.p':    'Danke für deine Nachricht. Ich melde mich innerhalb von 1–2 Werktagen bei dir.',

      /* ── PORTFOLIO PAGE ── */
      'p.hero.eyebrow':  'Tattoo Portfolio',
      'p.hero.h1':       'Portfolio &amp; <span>Stile</span>',
      'p.gallery.eyebrow': 'Galerie',
      'p.gallery.h2':    'Ausgewählte<br><span>Arbeiten</span>',
      'p.filter.all':    'Alle',
      'p.filter.bunt':   'Bunt',
      'p.filter.sw':     'Schwarz-Weiß',
      'p.filter.coverup':'Cover-Up',
      'p.filter.malerei':'Malerei',

      /* ── ANFAHRT PAGE ── */
      'anfahrt.hero.h1':   'Anfahrt &amp; <span>Lage</span>',
      'anfahrt.hero.desc': 'Das Atelier liegt in Bad Lippspringe, direkt an der Detmolder Strasse 119 – gut erreichbar aus Paderborn und Umgebung.',
      'anfahrt.bc':        'Anfahrt',
      'anfahrt.eyebrow':   'Finde das Tattoo Atelier für deine Auszeit',
      'anfahrt.h2':        'Adresse &amp; <span>Kontakt</span>',
      'anfahrt.lbl.address':'Adresse',
      'anfahrt.lbl.email': 'E-Mail',
      'anfahrt.lbl.hours': 'Öffnungszeiten',
      'anfahrt.hours.val': 'Nach Vereinbarung',
      'anfahrt.car.title': 'Mit dem Auto',
      'anfahrt.car.text':  'Bad Lippspringe liegt direkt an der B1, ca. 8 km östlich von Paderborn. Die Detmolder Strasse 119 ist gut ausgeschildert. Parkplätze sind in der Nähe vorhanden.',
      'anfahrt.bus.title': 'Mit dem ÖPNV',
      'anfahrt.bus.text':  'Vom Paderborner Hauptbahnhof mit dem Bus Richtung Bad Lippspringe. Haltestelle in der Nähe des Studios.',
      'anfahrt.gmaps':     'In Google Maps öffnen',

      /* ── PORTFOLIO PAGE (extended) ── */
      'p.hero.sub':        'Jeder Mensch ist einzigartig – sein Tattoo auch.<br>Hier findest du einen Überblick über meine Arbeiten und Spezialisierungen.',
      'p.bc':              'Portfolio &amp; Stile',
      'p.spec.eyebrow':    'Spezialisierungen',
      'p.spec.h2':         'Kunst, die <span>Eindruck macht!</span>',
      'p.spec.desc':       'Jedes Werk ein Unikat. Ich arbeite immer mit dem Anspruch, dass es dein persönliches Tattoo-Kunstwerk wird.',
      'p.card1.tag':       'Stil 01',
      'p.card1.h3':        'Bunt',
      'p.card1.desc':      'Lebendige Farben, die auf der Haut leuchten – Aquarell, Vollfarbe, florale Motive und Tierportraits in satter Brillanz.',
      'p.card2.tag':       'Stil 02',
      'p.card2.h3':        'Schwarz-Weiß',
      'p.card2.desc':      'Realismus, Feineline und Dotwork in Schwarz und Grau – präzise, zeitlos und ausdrucksstark.',
      'p.card3.tag':       'Stil 03',
      'p.card3.h3':        'Surrealismus &amp; Farbe',
      'p.card3.desc':      'Das Unmögliche, das durch Tinte real wird – surreale Welten, Dinos, Träume in satten Farben.',
      'p.card4.tag':       'Stil 04',
      'p.card4.h3':        'Cover-Ups',
      'p.card4.desc':      'Altes Tattoo? Kein Problem. Mit Kreativität und Technik entsteht an seiner Stelle etwas völlig Neues.',
      'p.card.more':       'Mehr erfahren',
      'p.stile.eyebrow':   'Spezialisierungen',
      'p.stile.h2':        'STILE &amp;<br><span>TECHNIKEN</span>',
      'p.s.spec':          'Spezialisierung',
      'p.s1.h2':           '<span>Bunt</span>',
      'p.s1.desc':         'Hier entstehen Motive mit Charakter – bunte florale Designs, eingerahmt von Ornamenten oder expressiven Brushstrokes. Kreative Freiheit trifft präzise Handwerkskunst.',
      'p.s2.h2':           '<span>Schwarz-Weiß</span>',
      'p.s2.desc':         'Auch im Black &amp; Grey steht Individualität im Mittelpunkt.',
      'p.s3.h2':           '<span>Surrealismus</span><br>&amp; Farbe',
      'p.s3.desc':         'Hier lebt das Unerwartete. Surreale Welten, unmögliche Kombinationen, Urlaub auf der Haut. Mit satten Farben und hohem Kontrast entsteht etwas, das du nirgendwo sonst findest. Ob Wannado oder eigene Idee. Kriegen wir hin.',
      'p.s4.h2':           '<span>Cover-Ups</span>',
      'p.s4.desc':         'Cover-Ups, die dir deinen Seelenfrieden bringen. Kein Tattoo muss für immer bleiben, wenn du es nicht willst – lass uns gemeinsam das Beste daraus machen.',
      'p.quote':           'EIN TATTOO IST <span style="color:var(--accent);">DAS EINZIGE</span> WAS DU DIR<br><span style="color:var(--accent);">IN DEINEM LEBEN</span> GÖNNST<br>OHNE ES JE WIEDER ZU VERLIEREN...',
      'p.cta.eyebrow':     'Welcher Stil ist deiner?',
      'p.cta.title':       'BEREIT FÜR<br>DEIN<br><span>TATTOO?</span>',
      'p.cta.btn':         'Termin anfragen',

      /* ── PFLEGE PAGE ── */
      'pflege.eyebrow':    'p-insel Tattoos · Pia Insel',
      'pflege.h1':         'Tattoo <em>Pflege</em>anleitung',
      'pflege.sub':        'Dein Tattoo ist frisch — so sorgst du dafür, dass es perfekt abheilt.',
      'pflege.printbar':   'Diese Seite als PDF speichern: Drucken → „Als PDF speichern" wählen',
      'pflege.printbtn':   'Als PDF speichern',
      'pflege.s1.h3':      'Warum Pflege so wichtig ist',
      'pflege.s1.p1':      'Wer sein Tattoo bei der Heilung richtig unterstützt und pflegt, hat lange Freude daran. Diese Zeit und Geduld zahlen sich auf jeden Fall aus.',
      'pflege.s1.p2':      'Dann bleibt die Haut geschmeidig und spannt weniger im Heilungsprozess. Außerdem besteht ein geringeres Risiko für Infektionen und es bilden sich <strong>keine Verkrustungen</strong>, bei denen Teile der Farbe mit abgetragen werden können. Dadurch profitiert das Tattoo, da keine Farblücken entstehen.',
      'pflege.s1.warn':    '<strong>Das Ergebnis:</strong> Schöne, gleichmäßige und langanhaltend strahlende Farben.',
      'pflege.s2.h3':      'Der Verband nach dem Tätowieren',
      'pflege.s2.p1':      'In aller Regel wird nach Vollendung ein <strong>Verband (Kompresse/Wickel)</strong> angelegt. Dieser schützt dein frisches Tattoo bis zum nächsten Tag.',
      'pflege.s2.p2':      'Nicht erschrecken — es ist völlig normal, wenn sich unter dem Verband Farbe und Wundsekret angesammelt haben. Das ist normal und dafür ist er gedacht.',
      'pflege.s3.h3':      '3 Wochen Tattoobehandlung — die oberste Regel',
      'pflege.s3.p1':      'Nun beginnt für die nächsten <strong>3 Wochen</strong> die heilende Tattoobehandlung.',
      'pflege.s3.warn':    '<strong>Die oberste Regel heißt: sauber halten!</strong>',
      'pflege.s3.p2':      '<strong>2–3× täglich</strong> mit einer pH-neutralen Seife das Tattoo abwaschen, bevor man es hauchdünn und mit sauberen Händen mit einer vorgesehenen Tattoo-Creme eincremt.',
      'pflege.s4.h3':      'Was unbedingt vermieden werden soll',
      'pflege.s4.p1':      'Direkte Sonneneinstrahlung, Kratzen, Rasieren und andere Reize sollen vermieden werden. Übermäßiger Konsum von Alkohol und Drogen sowie extreme Diäten können die Abheilung zusätzlich beeinflussen.',
      'pflege.s4.p2':      'Alles, was die Haut stark aufweicht, sollte vermieden werden:',
      'pflege.s4.li1':     'Eine normale Duschlänge ist kein Problem',
      'pflege.s4.li2':     '<strong>Baden, Schwimmen, Saunieren</strong> kann dem Tattoo sehr schaden',
      'pflege.s4.li3':     '<strong>Beim Sport schwitzen</strong> in den ersten Wochen meiden',
      'pflege.s4.li4':     '<strong>Zu viel cremen</strong> ist genauso schädlich wie zu wenig',
      'pflege.s4.warn':    'Nicht nur die <strong>Entzündungsgefahr</strong> ist bei solchen Situationen hoch — auch die <strong>Qualität des Tattoos</strong> kann in dieser kurzen Zeit dauerhaft leiden.',
      'pflege.s5.h3':      'Feine Linien brauchen Ruhe',
      'pflege.s5.p1':      'Die Tattoofarbe muss die Chance haben, in Ruhe und bester Qualität einzuwachsen. <strong>Feine Linien verlaufen eventuell</strong>, sobald die Haut zu sehr aufweicht und die Farbe noch nicht eingeheilt ist.',
      'pflege.s5.p2':      'Gib deinem Tattoo die Zeit, die es braucht — es trägt dich ein Leben lang.',
      'pflege.sig.p1':     'Vielen Dank für dein Vertrauen — und nun wünsche ich dir ganz viel Freude an deinem neuen Tattoo 🖤',
      'pflege.sig.p2':     'Pia Insel · p-insel.de · Bad Lippspringe',

      /* ── Google-Maps Consent (Klick-zum-Laden) ── */
      'map.consent.text':  'Hier wird eine Karte von Google Maps geladen. Dabei werden Daten an Google (USA) übertragen.',
      'map.consent.btn':   'Karte laden',
      'map.consent.note':  'Mit dem Laden akzeptierst du die <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Datenschutzerklärung von Google</a>.',

      /* ── LEGAL PAGES (Impressum / Datenschutz) ── */
      'legal.back':        '← Zurück zur Startseite',

      'imp.title':         'Impressum',
      'imp.h.tmg':         'Angaben gemäß § 5 DDG',
      'imp.addr':          'Pia Insel<br>p-insel<br>Detmolder Strasse 119<br>33175 Bad Lippspringe<br>Deutschland',
      'imp.h.contact':     'Kontakt',
      'imp.p.contact':     'E-Mail: <a href="mailto:info@p-insel.de">info@p-insel.de</a><br><small style="color:var(--text-dim);">(Diese Adresse ist ausschließlich für allgemeine Anfragen. Für Terminwünsche bitte das <a href="kontakt.html" style="color:var(--accent);">Kontaktformular</a> nutzen.)</small>',
      'imp.h.vat':         'Umsatzsteuer',
      'imp.p.vat':         'Entfällt gemäß § 19 Abs. 1 UStG (Kleinunternehmerregelung).',
      'imp.h.job':         'Berufsbezeichnung',
      'imp.p.job':         'Tätowiererin (selbstständig tätig in Deutschland)',
      'imp.h.responsible': 'Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV',
      'imp.p.responsible': 'Pia Insel<br>Detmolder Strasse 119<br>33175 Bad Lippspringe',
      'imp.h.liability':   'Haftungsausschluss',
      'imp.p.liability':   'Obwohl ich mich um die Aktualität, Vollständigkeit und Richtigkeit der Inhalte dieser Website bemühe, kann ich hierfür keine Garantie übernehmen. Gemäß § 7 Abs. 1 DDG bin ich als Dienstleisterin für eigene Inhalte nach den allgemeinen Gesetzen verantwortlich. Eine Verpflichtung zur Überwachung übermittelter oder gespeicherter fremder Informationen besteht jedoch nicht (§§ 8–10 DDG). Sobald mir Rechtsverstöße bekannt werden, werde ich die entsprechenden Inhalte umgehend entfernen.',
      'imp.h.links':       'Haftung für Links',
      'imp.p.links':       'Diese Website enthält ggf. Links auf externe Webseiten Dritter. Auf die Inhalte dieser verlinkten Webseiten habe ich keinen Einfluss. Für die Richtigkeit der Inhalte ist immer der jeweilige Anbieter oder Betreiber verantwortlich. Zum Zeitpunkt der Verlinkung waren keinerlei Rechtsverletzungen erkennbar. Falls mir Rechtsverletzungen bekannt werden, werde ich die entsprechenden Links sofort entfernen.',
      'imp.h.copyright':   'Urheberrecht',
      'imp.p.copyright':   'Die durch die Betreiberin dieser Seite erstellten Inhalte und Bilder unterliegen dem deutschen Urheberrecht. Sämtliche Beiträge Dritter sind als solche gekennzeichnet. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung der Betreiberin und sind nur für den privaten Bereich gestattet, nicht jedoch für kommerzielle Zwecke. Gleiches gilt für das Logo.',
      'imp.h.dispute':     'Verbraucherstreitbeilegung',
      'imp.p.dispute':     'Ich bin nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
      'imp.h.credits':     'Bildnachweis',
      'imp.p.credits':     'Alle auf dieser Website verwendeten Fotografien – Tattoo-Arbeiten, Atelierfotografien und Portraits – sind Eigentum von Pia Insel und urheberrechtlich geschützt.',

      'ds.title':          'Datenschutzerklärung',
      'ds.h1':             '1. Verantwortliche Stelle',
      'ds.p1':             'Pia Insel · p-insel Tattoos<br>Detmolder Strasse 119<br>33175 Bad Lippspringe<br>E-Mail: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'ds.h2':             '2. Erhebung und Verarbeitung personenbezogener Daten',
      'ds.p2':             'Personenbezogene Daten werden auf dieser Website nur im technisch notwendigen Umfang erhoben. In keinem Fall werden die erhobenen Daten verkauft oder aus anderen Gründen an Dritte weitergegeben, außer wie in dieser Datenschutzerklärung beschrieben.',
      'ds.h3':             '3. Server-Logfiles',
      'ds.p3':             'Der Hosting-Anbieter dieser Website erhebt und speichert automatisch Informationen in sogenannten Server-Log-Dateien, die Ihr Browser automatisch übermittelt. Dies sind: Browsertyp und Browserversion, verwendetes Betriebssystem, Referrer URL, Hostname des zugreifenden Rechners, Uhrzeit der Serveranfrage sowie IP-Adresse. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der technischen Bereitstellung der Website).',
      'ds.h4':             '4. Hosting',
      'ds.p4':             'Diese Website wird bei Netlify, Inc., 512 2nd Street, Suite 200, San Francisco, CA 94107, USA gehostet. Beim Abruf der Website werden technisch bedingt Daten (u. a. IP-Adresse) an die Server von Netlify übertragen. Netlify ist unter dem EU-US Data Privacy Framework zertifiziert. Weitere Informationen finden Sie in der Datenschutzerklärung von Netlify unter: <a href="https://www.netlify.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.netlify.com/privacy/</a>.',
      'ds.h5':             '5. Kontaktformular',
      'ds.p5':             'Wenn Sie uns über das Kontaktformular eine Anfrage senden, werden Ihre Angaben (Name, E-Mail-Adresse, Nachricht sowie ggf. hochgeladene Referenzbilder) zur Bearbeitung der Anfrage und für etwaige Anschlussfragen gespeichert. Der Versand des Formulars erfolgt technisch über den Dienst FormSubmit (betrieben in den USA), der die Formulardaten verarbeitet und als E-Mail an uns weiterleitet; dabei werden die übermittelten Daten an Server in den USA übertragen. Weitere Informationen: <a href="https://formsubmit.co/" target="_blank" rel="noopener noreferrer">formsubmit.co</a>. Darüber hinaus geben wir diese Daten nicht ohne Ihre Einwilligung weiter. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung) sowie Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an einer effizienten Bearbeitung). Die Daten werden gelöscht, sobald sie für die Erreichung des Zwecks nicht mehr erforderlich sind und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.',
      'ds.h6':             '6. Schriftarten (lokal gehostet)',
      'ds.p6':             'Diese Website verwendet Schriftarten (Barlow Condensed, Inter), die lokal auf unserem Server gespeichert sind. Eine Verbindung zu Servern von Google oder anderen externen Anbietern findet nicht statt.',
      'ds.h7':             '7. YouTube (Verlinkung)',
      'ds.p7':             'Diese Website enthält Links zu Videos auf YouTube (YouTube LLC, 901 Cherry Ave., San Bruno, CA 94066, USA; ein Dienst von Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland). Die Videos sind nicht direkt eingebettet – es werden erst dann Daten an YouTube bzw. Google übertragen, wenn Sie auf einen solchen Link klicken und die YouTube-Seite öffnen. Solange Sie nicht klicken, werden keine Daten an YouTube übermittelt. Weitere Informationen: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.',
      'ds.h8':             '8. Google Maps',
      'ds.p8':             'Auf dieser Website wird Google Maps der Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland eingebettet. Die Karte wird erst nach ausdrücklichem Klick auf „Karte laden“ aktiviert – bis dahin werden keine Daten an Google übertragen. Nach Aktivierung können Informationen über Ihre Nutzung dieser Website (einschließlich Ihrer IP-Adresse) an einen Server von Google in den USA übertragen werden. Weitere Informationen: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.',
      'ds.h9':             '9. Instagram (Verlinkung)',
      'ds.p9':             'Diese Website enthält einen Link zum Instagram-Profil der Betreiberin. Durch Klicken auf den Link verlassen Sie diese Website und werden zu Instagram (Meta Platforms Ireland Limited, 4 Grand Canal Square, Dublin 2, Irland) weitergeleitet. Die Datenverarbeitung durch Instagram erfolgt nach dem Klick auf den jeweiligen Link. Es werden keine Daten an Instagram übertragen, solange Sie nicht auf den Link klicken. Weitere Informationen finden Sie in der Datenschutzerklärung von Instagram: <a href="https://privacycenter.instagram.com/policy" target="_blank" rel="noopener noreferrer">https://privacycenter.instagram.com/policy</a>.',
      
      'ds.h9b':            '10. Facebook (Verlinkung)',
      'ds.p9b':            'Diese Website enthält einen Link zur Facebook-Seite der Betreiberin. Durch Klicken auf den Link verlassen Sie diese Website und werden zu Facebook (Meta Platforms Ireland Limited, 4 Grand Canal Square, Dublin 2, Irland) weitergeleitet. Es werden keine Daten an Facebook übertragen, solange Sie nicht auf den Link klicken. Weitere Informationen: <a href="https://www.facebook.com/privacy/explanation" target="_blank" rel="noopener noreferrer">https://www.facebook.com/privacy/explanation</a>.',
      'ds.h10':            '11. Cookies',
      'ds.p10':            'Diese Website verwendet ausschließlich technisch notwendige Cookies (z.B. für den Cookie-Hinweis/Cookie-Einwilligung). Es werden keine Tracking- oder Analyse-Cookies eingesetzt, solange Sie kein Video abspielen (siehe Abschnitt YouTube).',
      'ds.h11':            '12. Ihre Rechte als betroffene Person',
      'ds.p11':            'Sie haben gegenüber uns folgende Rechte hinsichtlich der Sie betreffenden personenbezogenen Daten:',
      'ds.r1':             '<strong>Recht auf Auskunft</strong> (Art. 15 DSGVO)',
      'ds.r2':             '<strong>Recht auf Berichtigung</strong> (Art. 16 DSGVO)',
      'ds.r3':             '<strong>Recht auf Löschung</strong> (Art. 17 DSGVO)',
      'ds.r4':             '<strong>Recht auf Einschränkung der Verarbeitung</strong> (Art. 18 DSGVO)',
      'ds.r5':             '<strong>Recht auf Datenübertragbarkeit</strong> (Art. 20 DSGVO)',
      'ds.r6':             '<strong>Recht auf Widerspruch gegen die Verarbeitung</strong> (Art. 21 DSGVO)',
      'ds.r7':             '<strong>Recht auf Widerruf</strong> einer erteilten Einwilligung (Art. 7 Abs. 3 DSGVO)',
      'ds.p11b':           'Zur Ausübung Ihrer Rechte wenden Sie sich an: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'ds.h12':            '13. Beschwerderecht bei der Aufsichtsbehörde',
      'ds.p12':            'Sie haben das Recht, sich bei einer Datenschutz-Aufsichtsbehörde über die Verarbeitung Ihrer personenbezogenen Daten durch uns zu beschweren. Zuständige Aufsichtsbehörde für Nordrhein-Westfalen ist:',
      'ds.p12b':           'Landesbeauftragte für Datenschutz und Informationsfreiheit NRW<br>Postfach 20 04 44, 40102 Düsseldorf<br><a href="https://www.ldi.nrw.de" target="_blank" rel="noopener noreferrer">www.ldi.nrw.de</a>',
      'ds.h13':            '14. Aktualität dieser Datenschutzerklärung',
      'ds.p13':            'Diese Datenschutzerklärung ist aktuell gültig und datiert vom Juni 2026. Durch die Weiterentwicklung unserer Website kann eine Anpassung dieser Datenschutzerklärung notwendig werden.',
      'ds.note':           'Hinweis: Diese Texte sind eine solide Grundlage. Zur weiteren Absicherung empfehlen wir einen Check über eRecht24.de oder einen Rechtsanwalt.',
    },

    en: {
      /* Nav & drawer */
      'nav.home':        'Home',
      'nav.portfolio':   'Portfolio',
      'nav.about':       'About',
      'nav.faq':         'FAQ',
      'nav.contact':     'Contact',
      'nav.cta':         'Book Appointment',
      'drawer.cta':      'Book Appointment',

      /* Hero */
      'hero.line1':      'YOUR',
      'hero.line2':      'TATTOO.',
      'hero.line3':      'FOREVER.',
      'hero.sub':        'Surrealism / Cover Up / Black &amp; Grey',
      'hero.location':   'Tattoo Studio · Bad Lippspringe',
      'hero.cta1':       'Book Appointment',
      'hero.cta2':       'View Portfolio',
      'hero.quote':      'A TATTOO IS <span style="color:var(--accent);">THE ONLY THING</span> YOU<br>GIVE YOURSELF <span style="color:var(--accent);">IN YOUR LIFE</span><br>WITHOUT EVER LOSING IT…',

      /* Stats bar */
      'stats.experience': 'Experience',
      'stats.tv':          'On TV',
      'stats.unique':      'Unique Pieces',
      'stats.since':       'Self-employed',
      'stats.events':      'Events',
      'stats.rating':      'Rating',

      /* About section (index) */
      'about.eyebrow':  'The Artist',
      'about.h2':       'Pia Insel –<br><span>Tattoo Artist</span><br>&amp; Painter',
      'about.quote':    '"Pia Insel is an exceptionally talented tattoo artist (…), known for her skills in watercolour, illustration and realism. Her work is a testament to her dedication and ability to bring each client\'s vision to life on their skin."',
      'about.cite':     '— Tattoo Wizard',
      'about.cta':      'More about Pia',
      'tag.realismus':  'Realism',
      'tag.tierportraits': 'Animal Portraits',
      'tag.surrealismus': 'Surrealism',
      'tag.dino':       'Dinosaurs',
      'tag.farbsw':     'Color &amp; B&amp;W',

      /* Stats section */
      'stats.label1':   'Years Experience',
      'stats.label2':   'Unique Pieces',
      'stats.label3':   'Conventions &amp; Events',
      'stats.label4':   'Google Rating',

      /* Portfolio teaser */
      'portfolio.eyebrow': 'Portfolio',
      'portfolio.title':   'Selected <span>Works</span>',
      'portfolio.all':     'All Works',
      'tag.bunt':    'Colorful',
      'tag.sw':      'Black &amp; White',
      'tag.coverup': 'Cover-Up',
      'tag.malerei': 'Paintings',

      /* SWR section */
      'swr.eyebrow':    'Known from TV',
      'swr.title':      'Pia Insel on <span>Television</span>',
      'swr.desc':       'Pia appeared twice on SWR – on "Kaffee oder Tee" she spoke about organ donation, and on Pierre M. Krause\'s show she provided "gute Unterhaltung".',
      'swr.card1.title':'Pia Insel on SWR',
      'swr.card1.desc': 'SWR loves to feature personalities who do something special. What tattoos have to do with organ donation.',
      'swr.card2.title':'Pia Insel on SWR',
      'swr.card2.desc': 'Pia brought great entertainment as a surprise guest on the topic of friendship.',
      'swr.yt.label':   'Watch on YouTube',

      /* Testimonials */
      'reviews.eyebrow': 'Customer Reviews',
      'reviews.title':   'What Customers <span>Say</span>',
      'review1.text':  'Pia is an absolutely fantastic artist. Super friendly, I immediately had complete trust in her. The studio is small and lovely, clean and cosy. And her work turned out beautifully.',
      'review1.name':  'Claudia S.',
      'review1.meta':  'Google Review · ★★★★★',
      'review2.text':  'Tattoo studio with a unique, magical atmosphere. Pia is super nice, warm, open and entertaining — her island is a cosy feel-good place. I\'m already looking forward to the next time!',
      'review2.name':  'Katrin Tonollo',
      'review2.meta':  'Google Review · ★★★★★',
      'review3.text':  'Pia has built not just a studio but a real feel-good place. Absolutely lovely. Pia as always very likeable and cheerful!',
      'review3.name':  'Jacqueline Bischel',
      'review3.meta':  'Google Review · ★★★★★',

      /* Maps */
      'maps.eyebrow':    'Getting Here',
      'maps.title':      'FIND THE TATTOO STUDIO <span>FOR YOUR PERSONAL RETREAT</span>',
      'maps.desc':       'The studio is right in the centre of Bad Lippspringe – on Detmolder Straße, easy to reach by car or bus.',
      'maps.address':    'Address',
      'maps.hours':      'Opening Hours',
      'maps.hours.val':  'By Appointment',
      'maps.gmaps':      'Open in Google Maps',

      /* Process */
      'process.eyebrow':  'How it works',
      'process.title':    'Your Path to <span>a Tattoo</span>',
      'process.s1.title': 'Wait for Appointment Release',
      'process.s1.desc':  'I release appointments once per quarter – since I organise everything on my own, I kindly ask for your patience. It will be worth it.',
      'process.s2.title': 'Gather Inspiration',
      'process.s2.desc':  'Collect reference images that show your desired style – photos of your pet, flowers or a favourite character.',
      'process.s3.title': 'Send Your Request',
      'process.s3.desc':  'Once appointments go live, send your request via the <a href="kontakt.html" style="color:var(--accent);text-decoration:none;">contact form</a>.',
      'process.s4.title': 'Secure Your Appointment',
      'process.s4.desc':  'If everything fits, your appointment will be confirmed. Then all that\'s left is to enjoy the anticipation and start the countdown.',

      /* Footer */
      'footer.about':        'Tattoo studio in Bad Lippspringe – where art is created and moments are captured for eternity. Pia Insel, tattoo artist &amp; painter.',
      'footer.nav.title':    'Navigation',
      'footer.styles.title': 'Styles',
      'footer.contact.title':'Contact',
      'footer.nav.home':     'Home',
      'footer.nav.portfolio':'Portfolio',
      'footer.nav.about':    'About',
      'footer.nav.styles':   'Styles &amp; Techniques',
      'footer.nav.contact':  'Contact',
      'footer.s.colorful':   'Colorful',
      'footer.s.bw':         'Black &amp; White',
      'footer.s.surreal':    'Surrealism &amp; Color',
      'footer.s.coverup':    'Cover-Ups',
      'footer.hours.label':  'Appointments',
      'footer.hours.val':    'By Appointment',

      /* Cookie */
      'cookie.text':    'This website uses no tracking cookies. Only technically necessary data is processed.',
      'cookie.accept':  'Got it',
      'cookie.decline': 'Close',

      /* ── KUENSTLERIN PAGE ── */
      'k.hero.eyebrow':  'The Artist',
      'k.hero.h1':       'Who is <span>Pia Insel?</span>',
      'k.about.eyebrow': 'About Me',
      'k.about.h2':      'PIA <span>INSEL</span>',
      'k.about.sub':     'Tattoo Artist · Stage Painter · Dreamer with a Needle.',
      'k.about.p1':      'I love <strong style="color:var(--text);">genuine people</strong>, good conversations and <strong style="color:var(--text);">honest energy</strong>. In my spare time I love to travel in all seasons and through all kinds of landscapes. I enjoy concerts just as much as staying home watching disaster documentaries or diving into completely unnecessary but fascinating geography facts.',
      'k.about.p2':      'Through my work I\'ve had the privilege of tattooing crew members for artists like <strong style="color:var(--text);">Rammstein, Peter Maffay and Jan Delay</strong> — and it\'s exactly this blend of creativity, people and special atmosphere that fulfils me. Work and life combined… as it should be!',
      'k.about.p3':      'My cat <strong style="color:var(--text);">Balu</strong> is firmly convinced he\'s a dog, which regularly gets me out of the house. He is <strong style="color:var(--text);">my star</strong> and I\'m endlessly grateful for him!',
      'k.about.p4':      'I\'m not exactly known for being reserved — I spread good vibes and have a serious soft spot for <strong style="color:var(--text);">dinosaurs</strong>.<br>And I move between laughter and deep talk surprisingly effortlessly.',
      'k.about.cta':     'Book Appointment Now',
      'k.tag.realismus':    'Realism',
      'k.tag.tierportraits':'Animal Portraits',
      'k.tag.surrealismus': 'Surrealism',
      'k.tag.dino':         'Dinosaurs',
      'k.tag.farbsw':       'Color &amp; B&amp;W',
      'k.tag.catmom':       'Cat Mom',
      'k.tag.ontour':       'On Tour',
      'k.tag.pinsel':       'Brush',

      /* Milestones */
      'k.milestones.eyebrow': 'Career',
      'k.milestones.title':   'Milestones',
      'k.m1.year':  '2015',
      'k.m1.title': 'Going Independent',
      'k.m1.desc':  'In 2015 I took the step into self-employment as a tattoo artist. After 12 years of stage painting, a new chapter began.',
      'k.m2.year':  '2016 – Today',
      'k.m2.title': 'Tattoo Conventions Across Europe',
      'k.m2.desc':  'I plan regular participation in international tattoo conventions and fairs throughout Europe.',
      'k.m3.year':  '2021',
      'k.m3.title': 'Own Studio',
      'k.m3.desc':  'After years of working alongside colleagues in various tattoo studios, I opened my own small private studio in 2021 — lovingly called the Island, as a play on my name.',
      'k.m4.year':  'Today',
      'k.m4.title': 'Back Home',
      'k.m4.desc':  'Happy to be back in my old hometown and excited for all the great projects waiting for me.',

      /* USP cards */
      'k.usp.eyebrow':  'Why p-insel',
      'k.usp.title':    'What sets me <span>apart</span>',
      'k.usp1.title':   'Artistic Background',
      'k.usp1.desc':    '12 years of stage painting shape every one of my tattoos. Composition, depth and perspective are my foundation.',
      'k.usp2.title':   'Consultation with Empathy',
      'k.usp2.desc':    'Even if we only meet for the first time on your big day, that doesn\'t mean you\'re just a number beforehand. That\'s exactly what makes your appointment and your tattoo so special in the end.',
      'k.usp3.title':   'Hygiene &amp; Safety',
      'k.usp3.desc':    'Sterile single-use materials, certified pigments and a clean studio. Your health is the top priority.',
      'k.usp4.title':   'Conventions &amp; Competitions',
      'k.usp4.desc':    'Regularly attending international tattoo conventions. Where the best artists in the scene come together.',

      /* Motto */
      'k.motto':      '"Today is your day. Take a holiday!<br>Your souvenir you\'ll carry forever."',
      'k.motto.attr': '— Pia Insel',

      /* CTA band */
      'k.cta.eyebrow':   'READY FOR YOUR TATTOO?',
      'k.cta.title':     '',
      'k.cta.btn':       'BOOK APPOINTMENT',

      /* ── FAQ PAGE ── */
      'faq.hero.eyebrow': 'Frequently Asked Questions',
      'faq.hero.h1':      'Everything you<br><em>need to know</em>',
      'faq.hero.sub':     'Questions about preparation and the process? Find your answers here.',

      /* FAQ questions */
      'faq.q1': 'What does a tattoo by Pia Insel cost?',
      'faq.q2': 'Do you ever decline requests?',
      'faq.q3': 'How do I find out if you can do my cover-up?',
      'faq.q4': 'How long does a tattoo appointment take?',
      'faq.q5': 'How do I pay?',
      'faq.q6': 'How do I prepare for my appointment?',
      'faq.q7': 'How do I care for my new tattoo?',

      /* FAQ answers */
      'faq.a1.p1': '<span style="color:#ffffff;font-weight:700;">Every tattoo is different</span> and depends on several factors: which body part is being tattooed, how large it is, and whether it will be very colourful or not.',
      'faq.a1.p2': 'In particular, the difference between a new tattoo design and a cover-up (tattooing over an old tattoo) should not be underestimated. A cover-up requires significantly more effort.',
      'faq.price.bunt':   'Colorful Tattoos &amp; Surrealism',
      'faq.price.coverup':'Cover-up Work',
      'faq.price.sw':     'Black &amp; White Work',
      'faq.a2.p1': 'I only take on projects that match my style. So if you come in with a Pinterest template and say "I want exactly this" — that\'s not going to happen. <strong>Inspiration is fine, but we don\'t do art theft!</strong>',
      'faq.a2.p2': 'I reserve the right to decline individual lettering, symbols and all motifs that don\'t give me any <span style="color:#ffffff;font-weight:700;">creative freedom</span>. I also don\'t tattoo areas like fingers, behind the ear, or anything below the ankle.',
      'faq.a3.p1': 'For such special cases I offer <strong>online consultations</strong> outside of the regular appointment windows. Consultation only — the actual appointment follows at the next quarterly release.',
      'faq.a3.p2': 'Please send me an email with:',
      'faq.a3.li1': 'a photo of your existing tattoo',
      'faq.a3.li2': 'images of your idea',
      'faq.a3.li3': 'a short description of what you have in mind',
      'faq.a3.mail': 'Email: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'faq.a4.p1': 'For a full-day session, plan for approx. <strong>6 hours</strong> — stress-free me-time, without interruptions, so I can fully focus on your tattoo dream.',
      'faq.a4.p2': 'For example: a complete arm (sleeve) takes me approx. <strong>4–6 appointments</strong>. Per day session I cover approx. an <strong>A4-sized area</strong> as a rough guide.',
      'faq.a5.p1': 'Payment can be made <strong>in cash</strong> or by <strong>instant bank transfer (online banking)</strong>. Instalment payments are not accepted.',
      'faq.a5.p2': 'Payment is due at the end of each appointment. If you end your session unexpectedly early, you are not entitled to a reduced price.',
      'faq.a6.li1':  '<span style="color:#ffffff;font-weight:700;">Get excited!</span>',
      'faq.a6.li2':  'Come to your appointment rested and relaxed',
      'faq.a6.li3':  'Treat yourself to something tasty and healthy beforehand — nothing too heavy',
      'faq.a6.li4':  'Bring a snack for longer sessions',
      'faq.a6.li5':  'Wear dark, comfortable clothing — e.g. a hoodie you can put on from the front, for back pieces',
      'faq.a6.li6':  '<strong>The studio is a shoe-free zone</strong> — bring thick socks or slippers',
      'faq.a6.li7':  'Bring a towel',
      'faq.a6.li8':  'If you\'re nervous: pack headphones and your favourite music',
      'faq.a6.li9':  'Trust your artist',
      'faq.a6.li10': '<strong>Quality time mode: on!</strong>',
      'faq.a7.p1': 'Once you finally have your long-awaited tattoo, I\'ll explain everything important about wound care. From this moment on, you are solely responsible for care and healing.',
      'faq.a7.p2': 'You can download the complete aftercare guide as a PDF here:',
      'faq.q8': 'What are the basic requirements for an appointment?',
      'faq.a8.p1': 'To make sure your appointment on the Insel runs smoothly, there are a few basic requirements:',
      'faq.a8.li1': 'Tattoos are only done <strong>from the age of 18</strong>',
      'faq.a8.li2': 'You should be in <strong>good overall health</strong>',
      'faq.a8.li3': 'Tattoos during <strong>pregnancy and breastfeeding</strong> are not possible',
      'faq.a8.li4': 'Before your appointment, please avoid <strong>blood-thinning and immune-weakening medication or foods</strong> (e.g. aspirin / alcohol), <strong>numbing creams</strong> and <strong>sunbathing</strong>',
      'faq.q9':      'Will I see my design before the appointment?',
      'faq.a9.p1':   'I show the final design on the day it gets tattooed. There is always <strong>enough time</strong> planned to make adjustments! No one is putting you under pressure – please don\'t hesitate to speak up.',
      'faq.a9.p2':   'This approach has proven itself over more than 12 years. Your detailed description and my artistic vision are the <strong>perfect combination</strong>.',
      'faq.pdf.title': 'Download Aftercare Guide',
      'faq.pdf.sub':   'PDF · Tattoo Aftercare by Pia Insel',

      /* FAQ CTA */
      'faq.cta.eyebrow': 'Ready?',
      'faq.cta.title':   'Your next tattoo<br><span>is waiting for you</span>',
      'faq.cta.desc':    'Send me your idea – and together we\'ll create something<br>you\'ll carry for a lifetime.',
      'faq.cta.btn':     'Send Appointment Request',

      /* ── KONTAKT PAGE ── */
      'kon.hero.eyebrow': 'Book Appointment',
      'kon.hero.h1':      'Let\'s get <span>started</span>',
      'kon.hero.sub':     'Describe your idea to me – I\'ll get back to you as soon as possible. Free initial consultation included.',
      'kon.info.eyebrow': 'How to Reach Me',
      'kon.info.h2':      'Contact &amp;<br><span>Info</span>',
      'kon.label.address':'Address',
      'kon.label.hours':  'Opening Hours',
      'kon.hours.val':    'By Appointment',
      'kon.pdf.title':    'Download Aftercare Guide',
      'kon.pdf.sub':      'PDF · Tattoo Aftercare by Pia Insel',
      'kon.form.booking': 'Booking Window',
      'kon.form.name':    'Name *',
      'kon.ph.name':      'Your name',
      'kon.form.email':   'Email *',
      'kon.ph.email':     'your@email.com',
      'kon.form.stil':    'Tattoo Style',
      'kon.form.groesse': 'Approximate Size',
      'kon.form.koerper': 'Body Placement',
      'kon.ph.koerper':   'e.g. back, shoulder, calf, forearm …',
      'kon.form.idee':    'Your Idea *',
      'kon.form.idee.ph': '• Main motif\n• Important details or elements\n• Desired mood/effect\n• What it should definitely include\n• What you don\'t want in the design\n• Preferred appointment period',
      'kon.form.refs':    'Reference Images (optional)',
      'kon.opt.please':   '– Please select –',
      'kon.stil.bunt':    'Colorful',
      'kon.stil.sw':      'Black &amp; White',
      'kon.stil.coverup': 'Cover-Up',
      'kon.size.a5':      'A5 size (approx. palm)',
      'kon.size.a4':      'A4 size (approx. upper arm)',
      'kon.size.arm':     'Full Arm / Sleeve',
      'kon.size.bein':    'Full Leg',
      'kon.size.ruecken': 'Full Back',
      'kon.body.unterarm':'Forearm',
      'kon.body.ruecken': 'Back',
      'kon.body.schulter':'Shoulder',
      'kon.body.wade':    'Calf',
      'kon.upload.text':  'Drop images here or <span style="color:var(--accent)">click</span>',
      'kon.upload.hint':  'JPG, PNG, HEIC — max. 5 MB per file',
      'kon.form.returning': 'Have you been to me before?',
      'kon.opt.yes':       'Yes',
      'kon.opt.no':        'No',
      'kon.form.hint':    '<strong style="color:var(--text);">Quick note before sending:</strong><br>Many questions about prices, styles, cover-ups and appointments are answered in the <a href="faq.html" style="color:var(--accent);">FAQ</a>. Feel free to check there first – your question might already be covered!',
      'kon.dsgvo':        'I have read the <a href="datenschutz.html" style="color:var(--accent);">Privacy Policy</a> and agree to the processing of my data. *',
      'kon.submit':       'Send Request',
      'kon.mandatory':    '* Required fields · Your data will not be shared with third parties',
      'kon.success.h3':   'Request received!',
      'kon.success.p':    'Thanks for your message. I\'ll get back to you within 1–2 business days.',

      /* ── PORTFOLIO PAGE ── */
      'p.hero.eyebrow':  'Tattoo Portfolio',
      'p.hero.h1':       'Portfolio &amp; <span>Styles</span>',
      'p.gallery.eyebrow': 'Gallery',
      'p.gallery.h2':    'Selected<br><span>Works</span>',
      'p.filter.all':    'All',
      'p.filter.bunt':   'Colorful',
      'p.filter.sw':     'Black &amp; White',
      'p.filter.coverup':'Cover-Up',
      'p.filter.malerei':'Paintings',

      /* ── ANFAHRT PAGE ── */
      'anfahrt.hero.h1':   'Directions &amp; <span>Location</span>',
      'anfahrt.hero.desc': 'The studio is in Bad Lippspringe, directly on Detmolder Strasse 119 – easy to reach from Paderborn and the surrounding area.',
      'anfahrt.bc':        'Directions',
      'anfahrt.eyebrow':   'Find the Tattoo Studio for your Retreat',
      'anfahrt.h2':        'Address &amp; <span>Contact</span>',
      'anfahrt.lbl.address':'Address',
      'anfahrt.lbl.email': 'E-Mail',
      'anfahrt.lbl.hours': 'Opening Hours',
      'anfahrt.hours.val': 'By Appointment',
      'anfahrt.car.title': 'By Car',
      'anfahrt.car.text':  'Bad Lippspringe is right on the B1 federal road, approx. 8 km east of Paderborn. Detmolder Strasse 119 is well signposted. Parking is available nearby.',
      'anfahrt.bus.title': 'By Public Transport',
      'anfahrt.bus.text':  'From Paderborn main station take the bus towards Bad Lippspringe. There\'s a stop near the studio.',
      'anfahrt.gmaps':     'Open in Google Maps',

      /* ── PORTFOLIO PAGE (extended) ── */
      'p.hero.sub':        'Every person is unique – so is their tattoo.<br>Browse my work and specialisations below.',
      'p.bc':              'Portfolio &amp; Styles',
      'p.spec.eyebrow':    'Specialisations',
      'p.spec.h2':         'Art that <span>Makes an Impression!</span>',
      'p.spec.desc':       'Every piece is one of a kind. I always aim for your tattoo to be your own personal work of art.',
      'p.card1.tag':       'Style 01',
      'p.card1.h3':        'Colourful',
      'p.card1.desc':      'Vibrant colours that glow on the skin – watercolour, full colour, floral motifs and animal portraits in rich brilliance.',
      'p.card2.tag':       'Style 02',
      'p.card2.h3':        'Black &amp; White',
      'p.card2.desc':      'Realism, fine line and dotwork in black and grey – precise, timeless and expressive.',
      'p.card3.tag':       'Style 03',
      'p.card3.h3':        'Surrealism &amp; Colour',
      'p.card3.desc':      'The impossible made real through ink – surreal worlds, dinos, dreams in vivid colours.',
      'p.card4.tag':       'Style 04',
      'p.card4.h3':        'Cover-Ups',
      'p.card4.desc':      'Old tattoo? No problem. With creativity and technique, something completely new takes its place.',
      'p.card.more':       'Learn more',
      'p.stile.eyebrow':   'Specialisations',
      'p.stile.h2':        'STYLES &amp;<br><span>TECHNIQUES</span>',
      'p.s.spec':          'Specialisation',
      'p.s1.h2':           '<span>Colourful</span>',
      'p.s1.desc':         'Motifs with character – colourful floral designs framed by ornaments or expressive brushstrokes. Creative freedom meets precise craftsmanship.',
      'p.s2.h2':           '<span>Black &amp; White</span>',
      'p.s2.desc':         'Individuality is at the heart of Black &amp; Grey work too.',
      'p.s3.h2':           '<span>Surrealism</span><br>&amp; Colour',
      'p.s3.desc':         'This is where the unexpected lives. Surreal worlds, impossible combinations, a holiday on your skin. Rich colours and high contrast create something you won\'t find anywhere else. Whether it\'s a wannado or your own idea – we\'ll make it happen.',
      'p.s4.h2':           '<span>Cover-Ups</span>',
      'p.s4.desc':         'Cover-ups that bring you peace of mind. No tattoo has to stay forever if you don\'t want it to – let\'s make the best of it together.',
      'p.quote':           'A TATTOO IS <span style="color:var(--accent);">THE ONLY THING</span> YOU<br>GIVE YOURSELF <span style="color:var(--accent);">IN YOUR LIFE</span><br>WITHOUT EVER LOSING IT...',
      'p.cta.eyebrow':     'Which style is yours?',
      'p.cta.title':       'READY FOR<br>YOUR<br><span>TATTOO?</span>',
      'p.cta.btn':         'Book Appointment',

      /* ── PFLEGE PAGE ── */
      'pflege.eyebrow':    'p-insel Tattoos · Pia Insel',
      'pflege.h1':         'Tattoo <em>After</em>care Guide',
      'pflege.sub':        'Your tattoo is fresh — here\'s how to make sure it heals perfectly.',
      'pflege.printbar':   'Save this page as PDF: Print → select "Save as PDF"',
      'pflege.printbtn':   'Save as PDF',
      'pflege.s1.h3':      'Why Aftercare Matters',
      'pflege.s1.p1':      'Proper care during healing means you\'ll enjoy your tattoo for years to come. The time and patience are absolutely worth it.',
      'pflege.s1.p2':      'It keeps the skin supple and reduces tightness during healing. It also lowers the risk of infection and prevents <strong>scabbing</strong>, which can lift colour and leave gaps in your tattoo.',
      'pflege.s1.warn':    '<strong>The result:</strong> Beautiful, even, long-lasting vibrant colours.',
      'pflege.s2.h3':      'The Bandage After Tattooing',
      'pflege.s2.p1':      'After your session a <strong>bandage (compress/wrap)</strong> will be applied. This protects your fresh tattoo until the next day.',
      'pflege.s2.p2':      'Don\'t be alarmed — it\'s completely normal for colour and wound fluid to collect under the bandage. That\'s exactly what it\'s there for.',
      'pflege.s3.h3':      '3 Weeks of Tattoo Care — The Golden Rule',
      'pflege.s3.p1':      'Now begins <strong>3 weeks</strong> of healing tattoo care.',
      'pflege.s3.warn':    '<strong>The golden rule: keep it clean!</strong>',
      'pflege.s3.p2':      '<strong>2–3 times daily</strong>, wash the tattoo with a pH-neutral soap, then apply a thin layer of dedicated tattoo cream with clean hands.',
      'pflege.s4.h3':      'What to Avoid',
      'pflege.s4.p1':      'Avoid direct sunlight, scratching, shaving and other irritants. Excessive alcohol, drugs and extreme diets can also affect healing.',
      'pflege.s4.p2':      'Anything that softens the skin heavily should be avoided:',
      'pflege.s4.li1':     'A normal shower length is fine',
      'pflege.s4.li2':     '<strong>Bathing, swimming, saunas</strong> can seriously damage the tattoo',
      'pflege.s4.li3':     'Avoid <strong>sweating during exercise</strong> in the first few weeks',
      'pflege.s4.li4':     '<strong>Too much cream</strong> is just as harmful as too little',
      'pflege.s4.warn':    'Not only is the <strong>risk of infection</strong> high in such situations — the <strong>quality of the tattoo</strong> can also suffer permanent damage during this short window.',
      'pflege.s5.h3':      'Fine Lines Need Rest',
      'pflege.s5.p1':      'The tattoo ink needs the chance to settle in at its best quality. <strong>Fine lines may blur</strong> if the skin softens too much before the colour has fully healed.',
      'pflege.s5.p2':      'Give your tattoo the time it needs — it will carry you for a lifetime.',
      'pflege.sig.p1':     'Thank you for your trust — and I wish you so much joy with your new tattoo 🖤',
      'pflege.sig.p2':     'Pia Insel · p-insel.de · Bad Lippspringe',

      /* ── Google Maps consent (click-to-load) ── */
      'map.consent.text':  'A Google Maps map will be loaded here. In doing so, data is transferred to Google (USA).',
      'map.consent.btn':   'Load map',
      'map.consent.note':  'By loading the map you accept Google\'s <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">privacy policy</a>.',

      /* ── LEGAL PAGES (Imprint / Privacy Policy) ── */
      'legal.back':        '← Back to homepage',

      'imp.title':         'Legal Notice',
      'imp.h.tmg':         'Information pursuant to § 5 DDG',
      'imp.addr':          'Pia Insel<br>p-insel<br>Detmolder Strasse 119<br>33175 Bad Lippspringe<br>Germany',
      'imp.h.contact':     'Contact',
      'imp.p.contact':     'Email: <a href="mailto:info@p-insel.de">info@p-insel.de</a><br><small style="color:var(--text-dim);">(This address is for general enquiries only. For appointment requests, please use the <a href="kontakt.html" style="color:var(--accent);">contact form</a>.)</small>',
      'imp.h.vat':         'VAT',
      'imp.p.vat':         'Not applicable under § 19 (1) UStG (small business regulation).',
      'imp.h.job':         'Professional title',
      'imp.p.job':         'Tattoo artist (self-employed in Germany)',
      'imp.h.responsible': 'Responsible for the content pursuant to § 18 (2) MStV',
      'imp.p.responsible': 'Pia Insel<br>Detmolder Strasse 119<br>33175 Bad Lippspringe',
      'imp.h.liability':   'Disclaimer',
      'imp.p.liability':   'Although I strive to keep the content of this website current, complete and accurate, I cannot guarantee this. Pursuant to § 7 (1) DDG, as a service provider I am responsible for my own content under the general laws. However, I am not obliged to monitor transmitted or stored third-party information (§§ 8–10 DDG). As soon as I become aware of any legal violations, I will remove the relevant content immediately.',
      'imp.h.links':       'Liability for links',
      'imp.p.links':       'This website may contain links to external third-party websites. I have no influence over the content of these linked websites. The respective provider or operator is always responsible for the accuracy of the content. No legal violations were apparent at the time the links were created. Should I become aware of any legal violations, I will remove the relevant links immediately.',
      'imp.h.copyright':   'Copyright',
      'imp.p.copyright':   'The content and images created by the operator of this site are subject to German copyright law. All third-party contributions are marked as such. Reproduction, editing, distribution and any kind of use beyond the limits of copyright require the written consent of the operator and are permitted for private use only, not for commercial purposes. The same applies to the logo.',
      'imp.h.dispute':     'Consumer dispute resolution',
      'imp.p.dispute':     'I am neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.',
      'imp.h.credits':     'Image credits',
      'imp.p.credits':     'All photographs on this website – tattoo work, studio photography and portraits – are the property of Pia Insel and protected by copyright.',

      'ds.title':          'Privacy Policy',
      'ds.h1':             '1. Controller',
      'ds.p1':             'Pia Insel · p-insel Tattoos<br>Detmolder Strasse 119<br>33175 Bad Lippspringe<br>Email: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'ds.h2':             '2. Collection and processing of personal data',
      'ds.p2':             'Personal data is collected on this website only to the extent technically necessary. Under no circumstances is the collected data sold or passed on to third parties for any other reason, except as described in this privacy policy.',
      'ds.h3':             '3. Server log files',
      'ds.p3':             'The hosting provider of this website automatically collects and stores information in so-called server log files, which your browser automatically transmits. These are: browser type and version, operating system used, referrer URL, hostname of the accessing computer, time of the server request and IP address. This data is not merged with other data sources. The legal basis is Art. 6 (1) (f) GDPR (legitimate interest in the technical provision of the website).',
      'ds.h4':             '4. Hosting',
      'ds.p4':             'This website is hosted by Netlify, Inc., 512 2nd Street, Suite 200, San Francisco, CA 94107, USA. When the website is accessed, technical data (including the IP address) is transmitted to Netlify\'s servers. Netlify is certified under the EU-US Data Privacy Framework. For more information, please see Netlify\'s privacy policy at: <a href="https://www.netlify.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.netlify.com/privacy/</a>.',
      'ds.h5':             '5. Contact form',
      'ds.p5':             'If you send us an enquiry via the contact form, your details (name, email address, message and any uploaded reference images) will be stored for the purpose of processing the enquiry and for any follow-up questions. The form is technically sent via the service FormSubmit (operated in the USA), which processes the form data and forwards it to us by email; in doing so, the transmitted data is transferred to servers in the USA. Further information: <a href="https://formsubmit.co/" target="_blank" rel="noopener noreferrer">formsubmit.co</a>. Beyond this, we do not pass on this data without your consent. The legal basis is Art. 6 (1) (b) GDPR (pre-contractual measures) and Art. 6 (1) (f) GDPR (legitimate interest in efficient processing). The data is deleted as soon as it is no longer required to achieve the purpose and no statutory retention obligations prevent this.',
      'ds.h6':             '6. Fonts (hosted locally)',
      'ds.p6':             'This website uses fonts (Barlow Condensed, Inter) that are stored locally on our server. No connection is made to servers of Google or other external providers.',
      'ds.h7':             '7. YouTube (links)',
      'ds.p7':             'This website contains links to videos on YouTube (YouTube LLC, 901 Cherry Ave., San Bruno, CA 94066, USA; a service of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland). The videos are not embedded directly – data is only transmitted to YouTube or Google once you click such a link and open the YouTube page. As long as you do not click, no data is transmitted to YouTube. Further information: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.',
      'ds.h8':             '8. Google Maps',
      'ds.p8':             'This website embeds Google Maps provided by Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. By using Google Maps, information about your use of this website (including your IP address) may be transmitted to and stored on a Google server in the USA. Google Maps is used to display our location. The legal basis is Art. 6 (1) (f) GDPR (legitimate interest in displaying the location). Further information on data protection at Google can be found at: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>. If you wish to object to data processing by Google Maps, disable JavaScript in your browser or use the “Open in Google Maps” link instead of the embedded map.',
      'ds.h9':             '9. Instagram (link)',
      'ds.p9':             'This website contains a link to the operator\'s Instagram profile. By clicking the link, you leave this website and are redirected to Instagram (Meta Platforms Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland). Data processing by Instagram takes place after you click the respective link. No data is transmitted to Instagram unless you click the link. For more information, please see Instagram\'s privacy policy: <a href="https://privacycenter.instagram.com/policy" target="_blank" rel="noopener noreferrer">https://privacycenter.instagram.com/policy</a>.',
      'ds.h9b':            '10. Facebook (link)',
      'ds.p9b':            'This website contains a link to the operator\'s Facebook page. By clicking the link, you leave this website and are redirected to Facebook (Meta Platforms Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland). No data is transmitted to Facebook unless you click the link. Further information: <a href="https://www.facebook.com/privacy/explanation" target="_blank" rel="noopener noreferrer">https://www.facebook.com/privacy/explanation</a>.',
      'ds.h10':            '11. Cookies',
      'ds.p10':            'This website uses exclusively technically necessary cookies (e.g. for the cookie notice/cookie consent). No tracking or analytics cookies are used unless you play a video (see the YouTube section).',
      'ds.h11':            '12. Your rights as a data subject',
      'ds.p11':            'You have the following rights with regard to the personal data concerning you:',
      'ds.r1':             '<strong>Right of access</strong> (Art. 15 GDPR)',
      'ds.r2':             '<strong>Right to rectification</strong> (Art. 16 GDPR)',
      'ds.r3':             '<strong>Right to erasure</strong> (Art. 17 GDPR)',
      'ds.r4':             '<strong>Right to restriction of processing</strong> (Art. 18 GDPR)',
      'ds.r5':             '<strong>Right to data portability</strong> (Art. 20 GDPR)',
      'ds.r6':             '<strong>Right to object to processing</strong> (Art. 21 GDPR)',
      'ds.r7':             '<strong>Right to withdraw</strong> consent given (Art. 7 (3) GDPR)',
      'ds.p11b':           'To exercise your rights, please contact: <a href="mailto:info@p-insel.de">info@p-insel.de</a>',
      'ds.h12':            '13. Right to lodge a complaint with a supervisory authority',
      'ds.p12':            'You have the right to lodge a complaint with a data protection supervisory authority about the processing of your personal data by us. The competent supervisory authority for North Rhine-Westphalia is:',
      'ds.p12b':           'Landesbeauftragte für Datenschutz und Informationsfreiheit NRW<br>Postfach 20 04 44, 40102 Düsseldorf<br><a href="https://www.ldi.nrw.de" target="_blank" rel="noopener noreferrer">www.ldi.nrw.de</a>',
      'ds.h13':            '14. Validity of this privacy policy',
      'ds.p13':            'This privacy policy is currently valid and dated June 2026. As our website develops further, it may become necessary to amend this privacy policy.',
      'ds.note':           'Note: These texts provide a solid basis. For further legal certainty, we recommend a check via eRecht24.de or a lawyer.',
    }
  };

  /* ──────────────────────────────────────────
     CORE FUNCTIONS
  ────────────────────────────────────────── */
  function getLang() {
    return localStorage.getItem(LANG_KEY) || 'de';
  }

  function applyLang(lang) {
    const t = T[lang];
    if (!t) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      if (t[key] !== undefined) {
        el.innerHTML = t[key];
      }
    });

    /* Placeholder-Übersetzung (Inputs / Textareas) */
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.dataset.i18nPlaceholder;
      if (t[key] !== undefined) {
        el.setAttribute('placeholder', t[key]);
      }
    });

    /* Update <html lang="…"> */
    document.documentElement.lang = lang;

    /* Update switcher button states on all switchers in page */
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === lang);
      btn.setAttribute('aria-pressed', btn.dataset.lang === lang ? 'true' : 'false');
    });

    localStorage.setItem(LANG_KEY, lang);

    /* Andere Skripte (z.B. das Buchungs-Widget auf der Kontaktseite) über den
       Sprachwechsel informieren, damit sie ihren dynamischen Inhalt neu rendern. */
    document.dispatchEvent(new CustomEvent('pi-langchange', { detail: lang }));
  }

  function init() {
    /* Wire up all .lang-btn elements */
    document.querySelectorAll('.lang-btn').forEach(btn => {
      btn.addEventListener('click', () => applyLang(btn.dataset.lang));
    });
    applyLang(getLang());
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
